# Generated by Django 5.1.7 on 2025-03-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Description de la tache si nécéssaire')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timer', models.TimeField(verbose_name='Temps avant répétition')),
            ],
        ),
    ]
