# Generated by Django 5.1.7 on 2025-03-22 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_time_done',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière fois que la tache a été effectuée'),
        ),
    ]
